//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.31 at 08:56:29 AM ICT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://nguyenviethung.com/department", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package jaxb;
