//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.04 at 05:16:38 PM ICT 
//
package duongpth.jaxbs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for recipe complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="recipe">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="link" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="image" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ration" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="preparetime" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="cookingtime" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="ingredientmenu" type="{http://www.ezco.com/XMLSchema/ezco}ingredientmenu" minOccurs="0"/>
 *         &lt;element name="instructionmenu" type="{http://www.ezco.com/XMLSchema/ezco}instructionmenu" minOccurs="0"/>
 *         &lt;element name="categories" type="{http://www.ezco.com/XMLSchema/ezco}categories" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "recipe", propOrder = {
    "id",
    "title",
    "link",
    "image",
    "description",
    "ration",
    "preparetime",
    "cookingtime",
    "ingredientmenu",
    "instructionmenu",
    "categories"
})
@XmlRootElement(name = "recipe")
public class Recipe {

    protected Integer id;
    protected String title;
    protected String link;
    protected String image;
    protected String description;
    protected Integer ration;
    @XmlElement(defaultValue = "10")
    protected Integer preparetime;
    @XmlElement(defaultValue = "20")
    protected Integer cookingtime;
    protected Ingredientmenu ingredientmenu;
    protected Instructionmenu instructionmenu;
    protected Categories categories;

    /**
     * Gets the value of the id property.
     *
     * @return possible object is {@link Integer }
     *
     */
    public Integer getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is {@link Integer }
     *
     */
    public void setId(Integer value) {
        this.id = value;
    }

    /**
     * Gets the value of the title property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the link property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getLink() {
        return link;
    }

    /**
     * Sets the value of the link property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setLink(String value) {
        this.link = value;
    }

    /**
     * Gets the value of the image property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getImage() {
        return image;
    }

    /**
     * Sets the value of the image property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setImage(String value) {
        this.image = value;
    }

    /**
     * Gets the value of the description property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the ration property.
     *
     * @return possible object is {@link Integer }
     *
     */
    public Integer getRation() {
        return ration;
    }

    /**
     * Sets the value of the ration property.
     *
     * @param value allowed object is {@link Integer }
     *
     */
    public void setRation(Integer value) {
        this.ration = value;
    }

    /**
     * Gets the value of the preparetime property.
     *
     * @return possible object is {@link Integer }
     *
     */
    public Integer getPreparetime() {
        return preparetime;
    }

    /**
     * Sets the value of the preparetime property.
     *
     * @param value allowed object is {@link Integer }
     *
     */
    public void setPreparetime(Integer value) {
        this.preparetime = value;
    }

    /**
     * Gets the value of the cookingtime property.
     *
     * @return possible object is {@link Integer }
     *
     */
    public Integer getCookingtime() {
        return cookingtime;
    }

    /**
     * Sets the value of the cookingtime property.
     *
     * @param value allowed object is {@link Integer }
     *
     */
    public void setCookingtime(Integer value) {
        this.cookingtime = value;
    }

    /**
     * Gets the value of the ingredientmenu property.
     *
     * @return possible object is {@link Ingredientmenu }
     *
     */
    public Ingredientmenu getIngredientmenu() {
        return ingredientmenu;
    }

    /**
     * Sets the value of the ingredientmenu property.
     *
     * @param value allowed object is {@link Ingredientmenu }
     *
     */
    public void setIngredientmenu(Ingredientmenu value) {
        this.ingredientmenu = value;
    }

    /**
     * Gets the value of the instructionmenu property.
     *
     * @return possible object is {@link Instructionmenu }
     *
     */
    public Instructionmenu getInstructionmenu() {
        return instructionmenu;
    }

    /**
     * Sets the value of the instructionmenu property.
     *
     * @param value allowed object is {@link Instructionmenu }
     *
     */
    public void setInstructionmenu(Instructionmenu value) {
        this.instructionmenu = value;
    }

    /**
     * Gets the value of the categories property.
     *
     * @return possible object is {@link Categories }
     *
     */
    public Categories getCategories() {
        return categories;
    }

    /**
     * Sets the value of the categories property.
     *
     * @param value allowed object is {@link Categories }
     *
     */
    public void setCategories(Categories value) {
        this.categories = value;
    }

    public boolean equals(Recipe o) {
        if (this.id == null || o.id == null) {
            throw new NullPointerException("Null Id");
        }
        return this.id - o.id == 0;
    }

}
